# Second Test Evaluation

In [2]:
#imports
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [23]:
#read data
labels = ['tile size','screen size','cam id 1','tiles cam 1','cam id 2','tiles cam 2', 'common tiles']
tilesizes = [8,16,32,64]
screensizes = [' 800x600',' 1024x768',' 1920x1080',' 3840x2160']
dataDict = {
    "sponza" : pd.read_csv("SecondTest\SecondTestSponza.csv",names =  labels),
    "lostEmpire" : pd.read_csv("SecondTest\SecondTestLostEmpire.csv",names =  labels),
}

In [24]:
def toPer(i):
    return "{0:.0f}%".format(i *100)

In [25]:
#add percentage data
for data in dataDict.values():
    data['% cam 1'] = data['common tiles']/data['tiles cam 1']
    data['% cam 2'] = data['common tiles']/data['tiles cam 2']

In [33]:
#group data
groupedData = data[['tile size','screen size','tiles cam 1','tiles cam 2', 'common tiles','% cam 1','% cam 2']].groupby(['tile size','screen size']).mean()

In [34]:
groupedData

                       tiles cam 1  tiles cam 2  common tiles   % cam 1  \
tile size screen size
8          1024x768        21551.1      18127.3        6910.8  0.321927
           1920x1080       32836.4      26351.6        9907.4  0.305108
           3840x2160       46603.6      35376.0       12247.0  0.269353
           800x600         18652.7      14473.3        6057.6  0.327460
16         1024x768         7832.8       6755.6        2629.8  0.337862
           1920x1080       11325.2       9290.4        3620.5  0.322696
           3840x2160       15157.1      11917.3        4305.8  0.289343
           800x600          7043.8       5748.6        2424.2  0.346692
32         1024x768         3475.6       3151.2        1293.0  0.375558
           1920x1080        4730.0       4049.2        1680.3  0.359011
           3840x2160        5776.1       4759.5        1862.7  0.327861
           800x600          3200.9       2807.9        1223.9  0.384994
64         1024x768         1666.1       1640.3         721.7  0.436928
           1920x1080        2258.1       2096.3         951.9  0.426339
           3840x2160        2678.2       2451.8        1068.1  0.405067
           800x600          1528.1       1449.5         685.3  0.450104

                        % cam 2
tile size screen size
8          1024x768    0.380188
           1920x1080   0.372978
           3840x2160   0.342338
           800x600     0.415704
16         1024x768    0.388309
           1920x1080   0.386798
           3840x2160   0.358395
           800x600     0.420198
32         1024x768    0.411453
           1920x1080   0.413831
           3840x2160   0.390220
           800x600     0.436713
64         1024x768    0.442353
           1920x1080   0.453860
           3840x2160   0.437480
           800x600     0.475203

In [88]:
df = pd.DataFrame([],columns=['tile size','1&2','1&3','1&4','1&5','2&3','2&4','2&5','3&4','3&5','4&5'])
i = 0
scene = "sponza"
for t in tilesizes:
    for s in screensizes:
        row = [t]
        for c1 in range(0,4):
            for c2 in range(c1+1,5):
                data = dataDict[scene]
                row += [data[(data["tile size"] == t) 
                        & (data["screen size"] == s) 
                        & (data["cam id 1"] == c1)
                        & (data["cam id 2"] == c2)]["% cam 1"].values[0]]
        df.loc[i] = row
        i += 1
    
print(df.to_latex())

\begin{tabular}{lrrrrrrrrrrr}
\toprule
{} &  tile size &       1\&2 &       1\&3 &       1\&4 &       1\&5 &       2\&3 &       2\&4 &       2\&5 &       3\&4 &       3\&5 &       4\&5 \\
\midrule
0  &        8.0 &  0.195621 &  0.084300 &  0.021249 &  0.009057 &  0.106920 &  0.047928 &  0.010950 &  0.048616 &  0.004100 &  0.024346 \\
1  &        8.0 &  0.179434 &  0.081060 &  0.018393 &  0.010868 &  0.106139 &  0.042482 &  0.009867 &  0.046643 &  0.003044 &  0.040247 \\
2  &        8.0 &  0.153633 &  0.062141 &  0.020602 &  0.009499 &  0.094257 &  0.053646 &  0.008774 &  0.058272 &  0.039971 &  0.120464 \\
3  &        8.0 &  0.191163 &  0.061879 &  0.027914 &  0.020707 &  0.096783 &  0.073187 &  0.019281 &  0.071018 &  0.067796 &  0.096721 \\
4  &       16.0 &  0.258916 &  0.169995 &  0.051355 &  0.023300 &  0.187712 &  0.086175 &  0.029550 &  0.080489 &  0.021471 &  0.037514 \\
5  &       16.0 &  0.236508 &  0.150592 &  0.041522 &  0.021501 &  0.176434 &  0.073873 &  0.024385 &  0.075200 &  0.015701 &  0.047561 \\
6  &       16.0 &  0.202840 &  0.119682 &  0.038402 &  0.018787 &  0.153703 &  0.081441 &  0.021879 &  0.084178 &  0.048400 &  0.117833 \\
7  &       16.0 &  0.233497 &  0.106216 &  0.036235 &  0.025865 &  0.148341 &  0.087658 &  0.024676 &  0.082398 &  0.062345 &  0.096651 \\
8  &       32.0 &  0.346731 &  0.291274 &  0.117527 &  0.058509 &  0.309062 &  0.166579 &  0.077004 &  0.153914 &  0.066814 &  0.082258 \\
9  &       32.0 &  0.311828 &  0.255760 &  0.094470 &  0.050883 &  0.289187 &  0.142917 &  0.062238 &  0.137854 &  0.053562 &  0.079783 \\
10 &       32.0 &  0.278653 &  0.213991 &  0.083893 &  0.048658 &  0.252953 &  0.147962 &  0.059510 &  0.142719 &  0.080930 &  0.141500 \\
11 &       32.0 &  0.293803 &  0.183197 &  0.066803 &  0.041386 &  0.233208 &  0.136543 &  0.052467 &  0.125743 &  0.072003 &  0.110273 \\
12 &       64.0 &  0.439937 &  0.419389 &  0.199157 &  0.126976 &  0.436799 &  0.272681 &  0.162080 &  0.240086 &  0.145690 &  0.185606 \\
13 &       64.0 &  0.403335 &  0.385867 &  0.180230 &  0.116316 &  0.418567 &  0.241042 &  0.140472 &  0.225343 &  0.122367 &  0.163335 \\
14 &       64.0 &  0.382517 &  0.352728 &  0.168151 &  0.108296 &  0.394292 &  0.261794 &  0.135993 &  0.241553 &  0.152169 &  0.217515 \\
15 &       64.0 &  0.381131 &  0.312042 &  0.137852 &  0.086687 &  0.372249 &  0.242447 &  0.113204 &  0.213139 &  0.118102 &  0.171142 \\
\bottomrule
\end{tabular}

In [89]:
df2 = df.groupby(['tile size']).mean()

for old_col in df2:
    new_col = [] 
    for val in df2[old_col]:
        new_col += [toPer(val)]
    df2[old_col] = new_col

print(df2.to_latex())

\begin{tabular}{lllllllllll}
\toprule
{} &  1\&2 &  1\&3 &  1\&4 &  1\&5 &  2\&3 &  2\&4 &  2\&5 &  3\&4 &  3\&5 &  4\&5 \\
tile size &      &      &      &      &      &      &      &      &      &      \\
\midrule
8.0       &  18\% &   7\% &   2\% &   1\% &  10\% &   5\% &   1\% &   6\% &   3\% &   7\% \\
16.0      &  23\% &  14\% &   4\% &   2\% &  17\% &   8\% &   3\% &   8\% &   4\% &   7\% \\
32.0      &  31\% &  24\% &   9\% &   5\% &  27\% &  15\% &   6\% &  14\% &   7\% &  10\% \\
64.0      &  40\% &  37\% &  17\% &  11\% &  41\% &  25\% &  14\% &  23\% &  13\% &  18\% \\
\bottomrule
\end{tabular}